service: weather-notifications

custom:
  defaultStage: dev

provider:
  name: aws
  runtime: provided
  timeout: 300
  region: ap-northeast-1
  ecr:
    images:
      appImage:
        path: ./
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    ${file(./env.yml)}

functions:
  weather_notifications:
    image:
      name: appImage
      command:
        - weather_notifications
    events:
      - schedule: cron(10 20 * * ? *) # UTC
