service: weather-notifications

custom:
  defaultAccount: dummy
  defaultDigest: dummy
  defaultStage: dev

provider:
  name: aws
  runtime: provided
  timeout: 300
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    ${file(./env.yml)}

functions:
  weather_notifications:
    image: ${opt:account, self:custom.defaultAccount}.dkr.ecr.${self:provider.region}.amazonaws.com/weather_notifications_${self:provider.stage}@${opt:digest, self:custom.defaultDigest}
    events:
      - schedule: cron(10 20 * * ? *) # UTC
